logging:
  config: classpath:log4j.properties
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/belajarspringdatajpa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update